#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
YEAR_MONTH=$(date '+%Y%m%d')
SCRIPT_FILE="$SCRIPT_DIR/tofan"
CONFIG_FILE="$SCRIPT_DIR/tofan.config"
. "${CONFIG_FILE}"
DOCKER_COMPOSE=${DOCKER_PATH}docker-compose.yml
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
TOFAN_VERSION=1-04072023
TEXT_COLOR=${NC}
echo -e ${TEXT_COLOR}
echo "=====================TOFAN script v${DWC_VERSION}========================="
if [ "$1" == "help" ]; then
  echo "Command version ${TOFAN_VERSION}"
  echo "Use command below"
  echo "============================================================="
  echo "Format: tofan.sh <command>"
  echo "============================================================="
  echo "version         : show script version"
  echo "link            : *create a link to /usr/local/bin/"
  echo "docker rebuild  : docker rebuild all containers"
  echo "docker start    : docker start all containers"
  echo "docker stop     : docker stop all containers"
  echo "docker open <container> : *docker goto <container>"
  echo "Description with prefix * need root privilege"
  exit 0
fi
if [ "$1" == "version" ]; then
  echo "Shorcut Script v${TOFAN_VERSION}"
  exit 0
fi
if [ "$1" == "link" ]; then
  SCRIPT_LINK=/usr/local/bin/tofan
  CONFIG_LINK=/usr/local/bin/tofan.config
  if [ -f "$SCRIPT_LINK" ]; then
    rm $SCRIPT_LINK
  fi
  if [ -L "$SCRIPT_LINK" ]; then
    rm $SCRIPT_LINK
  fi
  if [ -L "$CONFIG_LINK" ]; then
    rm $CONFIG_LINK
  fi
  ln -s ${SCRIPT_FILE} ${SCRIPT_LINK}
  ln -s ${CONFIG_FILE} ${CONFIG_LINK}
  echo "Link ${SCRIPT_LINK} created"
  exit 0
fi
if [ "$1" == "docker" ]; then
  if [ "$2" == "rebuild" ]; then
    #rebuild and restart docker
    status2=$(docker images -f "dangling=true" -q | wc -l)
    # Delete all none images
    if [ $status2 -gt 0 ]; then
        echo "images not empty, removing them..."
        #docker rmi $(docker images -q)
        docker rmi $(docker images -f "dangling=true" -q)
        #docker network prune
        echo "done"
    fi
    #docker network create as_bridge;
    docker-compose -f ${DOCKER_COMPOSE} up --build -d 
    docker-compose -f ${DOCKER_COMPOSE} ps
    exit 0
  fi
  if [ "$2" == "start" ]; then
    docker-compose -f ${DOCKER_COMPOSE} stop
    docker-compose -f ${DOCKER_COMPOSE} start
    docker-compose -f ${DOCKER_COMPOSE} ps
    exit 0
  fi
  if [ "$2" == "stop" ]; then
    docker-compose -f ${DOCKER_COMPOSE} stop;
    docker-compose -f ${DOCKER_COMPOSE} ps;
    exit 0
  fi
  if [ "$2" == "open" ]; then
    if [ "$4" == "root" ]; then
      docker exec -it -uroot $3 sh
      exit 0
    fi
    docker exec -it -uwww-data $3 sh
    exit 0 
  fi
  exit 0
fi
echo "Finish"
