FROM php:8.1-fpm-alpine

ENV HOME /www-data

USER root

RUN apk add --no-cache \
    $PHPIZE_DEPS \
    openssl-dev \
    linux-headers \
    git \
    libzip-dev \
    zip \
    grep \
    libpng-dev \
    nodejs \
    yarn \
    icu-dev

RUN docker-php-source extract \
    && docker-php-ext-install pdo_mysql gd zip intl mysqli \
    && docker-php-source delete

COPY config/php-redis.ini /usr/local/etc/php/php.ini

# install composer
RUN curl -sS https://getcomposer.org/installer | php \
    -- --install-dir=/usr/local/bin --filename=composer

USER www-data
WORKDIR /var/www
EXPOSE 9000